### ISSUE TITLE
Sprint 3,4 Video

### ISSUE THREAD

**Issue by gigiguan** [gigiguan/flask_portfolio#11]
https://user-images.githubusercontent.com/89219435/133844775-480d11b1-34a3-4911-945d-39520b99c68c.mp4

**Comment by christinlee367** [comment]
Looking at individual commit...
Gigi work is very technical including ascii. Very impressive 2/2
Shruti did visualization of binary and research and theme as her technical as well 2/2
Jessie attempted to do the RGB in the binary.html technical work 2/2
Neha worked on own research and Theme,Though I see he made a page 2/2.0
Great teamwork in making the video as well.

I looked at the READ.ME and would like to see more linking and in depth with the description to make it easier for the grader. I would also want to see the self grade in the READ.ME instead of the scrum board.
Looked at all journals. It is very descriptive but it would be better if most recent stuff is placed on top. 
Also, I would have one link on README to Issue and then put link(s) on Issue. Links can help the grader and whomever is looking to make it easier to look at.
I love how you guys included links to your own individual contributions and hope you each will continue to work hard and get more commits.

**Comment by christinlee367** [comment]
Looking at team accomplishments. The video of your tasks and in progress unique characteristics of your website is great and I also love the including of ascii, I'm sure it wasn't easy. I would work on making a table for your READ.ME to make it more descriptive and organized than a long paragraph of information. The most amazing thing would be your overall design because it is great and potentially amazing to see. I will look forward to the end result.
2/2 team + 1/1 for planning
